apiVersion: apps/v1
kind: Deployment
metadata:
  name: runthis-server-deployment
  labels:
    app: runthis-server
spec:
  selector:
    matchLabels:
      app: runthis-server
  template:
    metadata:
      labels:
        app: runthis-server
    spec:
      containers:
      - name: runthis-server-container
        image: ghcr.io/anthony-bible/script-server:latest
        imagePullPolicy: "Always"
